INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (1, 'Sem categoria', 'sem-categoria', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (2, 'Cadernos', 'cadernos', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (3, 'eva', 'eva', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (4, 'capa de caderno', 'capa-de-caderno', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (5, 'artesanato', 'artesanato', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (6, 'sônia grillo', 'sonia-grillo', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (7, 'vídeo aula', 'video-aula', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (8, 'aula gratuita', 'aula-gratuita', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (9, 'arte em dois', 'arte-em-dois', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (10, 'Festas', 'festas', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (11, 'Bonecos', 'bonecos', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (12, 'festas', 'festas', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (13, 'galinha pintadinha', 'galinha-pintadinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (14, 'decoração festas', 'decoracao-festas', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (15, 'bonecos', 'bonecos', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (16, 'tania peçanha', 'tania-pecanha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (17, 'turma do chaves', 'turma-do-chaves', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (18, 'menino maluquinho', 'menino-maluquinho', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (19, 'super herois', 'super-herois', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (20, 'palhaços', 'palhacos', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (21, 'mario bros', 'mario-bros', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (22, 'Recicláveis', 'reciclaveis', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (23, 'Lembrancinhas', 'lembrancinhas', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (24, 'Chaveiros', 'chaveiros', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (25, 'Porta retratos', 'porta-retratos', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (26, 'Convites', 'convites', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (27, 'Porta recados', 'porta-recados', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (28, 'Casamento', 'casamento', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (29, 'porta treco', 'porta-treco', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (30, 'burrinho', 'burrinho', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (31, 'reciclável', 'reciclavel', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (32, 'garrafa pet', 'garrafa-pet', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (33, 'ovelhinha', 'ovelhinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (34, 'mulher maravilha', 'mulher-maravilha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (35, 'lembrancinha', 'lembrancinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (36, 'artesanato lucrativo', 'artesanato-lucrativo', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (37, 'batman', 'batman', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (38, 'super-homem', 'super-homem', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (39, 'pequeno principe', 'pequeno-principe', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (40, 'aniversario', 'aniversario', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (41, 'bailarina', 'bailarina', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (42, 'video', 'video', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (43, 'chaveiro', 'chaveiro', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (44, 'joaninha', 'joaninha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (45, 'cestinha', 'cestinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (46, 'arranjo de mesa', 'arranjo-de-mesa', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (47, 'bolo de fraldas', 'bolo-de-fraldas', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (48, 'porta retrato', 'porta-retrato', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (49, 'porta bombons', 'porta-bombons', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (50, 'festa', 'festa', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (51, 'minions', 'minions', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (52, 'laço de cetim', 'laco-de-cetim', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (53, 'arte com papelão', 'arte-com-papelao', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (54, 'chá de bebê', 'cha-de-bebe', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (55, 'chá de lingerie', 'cha-de-lingerie', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (56, 'cartolina', 'cartolina', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (57, 'porta recados', 'porta-recados', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (58, 'renda extra', 'renda-extra', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (59, 'artesão lucrativo', 'artesao-lucrativo', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (60, 'moldes', 'moldes', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (61, 'tema abelhinha', 'tema-abelhinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (62, 'girafa', 'girafa', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (63, 'florzinha', 'florzinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (64, 'sala de aula', 'sala-de-aula', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (65, 'casamento', 'casamento', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (66, 'economia', 'economia', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (67, 'noivo', 'noivo', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (68, 'bem casado', 'bem-casado', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (69, 'noivinho', 'noivinho', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (70, 'noiva', 'noiva', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (71, 'noivinha', 'noivinha', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (72, 'dia dos pais', 'dia-dos-pais', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (73, 'menina', 'menina', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (74, 'menino', 'menino', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (75, 'tubete decorado', 'tubete-decorado', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (76, 'palhaço', 'palhaco', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (77, 'ponteira', 'ponteira', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (78, 'embalagem', 'embalagem', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (79, 'bolo fake casamento', 'bolo-fake-casamento', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (80, '10 ideias', '10-ideias', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (81, 'biscuit', 'biscuit', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (82, 'diy', 'diy', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (83, 'hora de aventura', 'hora-de-aventura', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (84, 'beemo', 'beemo', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (85, 'jake', 'jake', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (86, 'cachorro', 'cachorro', 0);
INSERT INTO arte_em_dois.ad_terms (term_id, name, slug, term_group) VALUES (87, 'finn', 'finn', 0);