INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (1, 1, 'category', '', 0, 0);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (2, 2, 'category', 'Tutoriais sobre cadernos artesanais passo a passo, cadernos artesanais em tecido, cadernos artesanais em fita, cadernos de receitas artesanais e cadernos personalizados.', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (3, 3, 'post_tag', '', 0, 26);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (4, 4, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (5, 5, 'post_tag', '', 0, 12);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (6, 6, 'post_tag', '', 0, 8);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (7, 7, 'post_tag', '', 0, 10);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (8, 8, 'post_tag', '', 0, 10);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (9, 9, 'post_tag', '', 0, 36);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (10, 10, 'category', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (11, 11, 'category', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (12, 12, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (13, 13, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (14, 14, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (15, 15, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (16, 16, 'post_tag', '', 0, 30);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (17, 17, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (18, 18, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (19, 19, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (20, 20, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (21, 21, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (22, 22, 'category', 'Tutoriais sobre artesanato reciclável passo a passo, artesanato reciclável com garrafa pet e artesanato reciclável com eva.', 0, 4);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (23, 23, 'category', 'Tutoriais sobre lembrancinhas eva para aniversário, lembrancinhas eva com doce, lembrancinhas evangélicas, lembrancinhas eva dia das mães e lembrancinhas eva para meninas.', 0, 17);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (24, 24, 'category', 'Tutoriais sobre chaveiros artesanais passo a passo, chaveiros artesanais de tecido, chaveiros artesanais de feltro e chaveiros artesanais em eva.', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (25, 25, 'category', 'Tutoriais sobre porta retratos de parede artesanais, porta retratos criativos reciclados, porta retratos diferentes e ainda mais porta retratos criativos.', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (26, 26, 'category', 'Tutoriais sobre convites de aniversário, convites de casamento, convites de 15 anos, convites simples, convites diferentes e modelos de convites.', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (27, 27, 'category', 'Tutoriais sobre porta recados de parede, porta recados de mesa, porta recados artesanal, porta recados com CD, porta recados de EVA e porta recados tecido.', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (28, 28, 'category', 'Tutoriais sobre lembrancinhas de casamento, convites de casamento, arranjos para casamento, dicas de casamento econômico, noivinhos e forminhas.', 0, 10);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (29, 29, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (30, 30, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (31, 31, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (32, 32, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (33, 33, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (34, 34, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (35, 35, 'post_tag', '', 0, 16);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (36, 36, 'post_tag', '', 0, 17);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (37, 37, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (38, 38, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (39, 39, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (40, 40, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (41, 41, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (42, 42, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (43, 43, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (44, 44, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (45, 45, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (46, 46, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (47, 47, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (48, 48, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (49, 49, 'post_tag', '', 0, 6);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (50, 50, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (51, 51, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (52, 52, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (53, 53, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (54, 54, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (55, 55, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (56, 56, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (57, 57, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (58, 58, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (59, 59, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (60, 60, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (61, 61, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (62, 62, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (63, 63, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (64, 64, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (65, 65, 'post_tag', '', 0, 10);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (66, 66, 'post_tag', '', 0, 4);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (67, 67, 'post_tag', '', 0, 4);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (68, 68, 'post_tag', '', 0, 6);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (69, 69, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (70, 70, 'post_tag', '', 0, 4);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (71, 71, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (72, 72, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (73, 73, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (74, 74, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (75, 75, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (76, 76, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (77, 77, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (78, 78, 'post_tag', '', 0, 2);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (79, 79, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (80, 80, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (81, 81, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (82, 82, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (83, 83, 'post_tag', '', 0, 3);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (84, 84, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (85, 85, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (86, 86, 'post_tag', '', 0, 1);
INSERT INTO arte_em_dois.ad_term_taxonomy (term_taxonomy_id, term_id, taxonomy, description, parent, count) VALUES (87, 87, 'post_tag', '', 0, 1);