INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (1, 1, 'nickname', 'adminwp@gmail.com');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (2, 1, 'first_name', 'Equipe Arte em Dois');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (3, 1, 'last_name', 'Arte em Dois');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (4, 1, 'description', 'A equipe Arte em Dois envolve programadores e outros profissionais que são responsáveis por manter o projeto Arte em Dois online.');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (5, 1, 'rich_editing', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (6, 1, 'comment_shortcuts', 'false');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (7, 1, 'admin_color', 'fresh');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (8, 1, 'use_ssl', '0');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (9, 1, 'show_admin_bar_front', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (10, 1, 'locale', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (11, 1, 'ad_capabilities', 'a:1:{s:13:"administrator";b:1;}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (12, 1, 'ad_user_level', '10');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (13, 1, 'dismissed_wp_pointers', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (14, 1, 'show_welcome_panel', '1');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (15, 1, 'session_tokens', 'a:2:{s:64:"6f28a36e4893892152ecac0eab4a9fea268ad84d8613ed0486985560bacb9350";a:4:{s:10:"expiration";i:1501161809;s:2:"ip";s:3:"::1";s:2:"ua";s:121:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36";s:5:"login";i:1500989009;}s:64:"0e122a9331464675a2e7f545ccff198253af2a653c67a7260be21065267371bc";a:4:{s:10:"expiration";i:1501183692;s:2:"ip";s:3:"::1";s:2:"ua";s:121:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36";s:5:"login";i:1501010892;}}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (16, 1, 'ad_dashboard_quick_press_last_post_id', '3');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (17, 1, 'community-events-location', 'a:1:{s:2:"ip";s:2:"::";}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (18, 1, 'ad_user-settings', 'libraryContent=browse&editor=tinymce&advImgDetails=show');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (19, 1, 'ad_user-settings-time', '1500902240');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (20, 1, 'hu_last_tgmpa_notice', 'a:2:{s:7:"version";s:6:"3.3.18";s:13:"dismiss_count";i:0;}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (21, 2, 'nickname', 'tania.arteemdois@gmail.com');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (22, 2, 'first_name', 'Tânia');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (23, 2, 'last_name', 'Peçanha');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (24, 2, 'description', 'Tania Peçanha é artesã e empreendedora no ramo de artesanato. Depois de anos ensinando em salas de aula e atendendo a clientes, juntou-se a Sônia Grillo para fundar o Arte em Dois. Ambiente online de capacitação de artesãos.');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (25, 2, 'rich_editing', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (26, 2, 'comment_shortcuts', 'false');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (27, 2, 'admin_color', 'fresh');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (28, 2, 'use_ssl', '0');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (29, 2, 'show_admin_bar_front', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (30, 2, 'locale', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (31, 2, 'ad_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (32, 2, 'ad_user_level', '2');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (33, 2, 'dismissed_wp_pointers', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (34, 3, 'nickname', 'sonia.arteemdois@gmail.com');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (35, 3, 'first_name', 'Sônia');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (36, 3, 'last_name', 'Grillo');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (37, 3, 'description', 'Sônia Grillo é artesã e empreendedora no ramo de artesanato. Depois de anos ensinando em salas de aula e atendendo a clientes, juntou-se a Tania Peçanha para fundar o Arte em Dois. Ambiente online de capacitação de artesãos.');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (38, 3, 'rich_editing', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (39, 3, 'comment_shortcuts', 'false');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (40, 3, 'admin_color', 'fresh');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (41, 3, 'use_ssl', '0');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (42, 3, 'show_admin_bar_front', 'true');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (43, 3, 'locale', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (44, 3, 'ad_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (45, 3, 'ad_user_level', '2');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (46, 3, 'dismissed_wp_pointers', '');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (47, 2, 'ad_user_avatar', '37');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (48, 3, 'ad_user_avatar', '38');
INSERT INTO arte_em_dois.ad_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (49, 1, 'ad_user_avatar', '181');